spring:
  applcation:
    name: RestMongo
  data:
    mongodb:
      uri: mongodb://localhost:27017/Rest
server:
  port: 8080

management:
  health:
    show-deatils: always
  endpoints:
    web:
      exposure:
        include: "*"
