spring:
  applcation:
    name: RestMongo
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/Rest # if mongodb is running on the container, give the internal container ip
server:
  port: 8080

management:
  health:
    show-deatils: always
  endpoints:
    web:
      exposure:
        include: "*"
